# Generated by Django 6.1 on 2026-08-15 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('monthly_rent', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room')], max_length=20)),
                ('available_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
